spring.application.name=auth-service


server.port=8080


spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mediccare_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=${JWT_SECRET:change-me-to-a-secure-secret-key-at-least-256-bits}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
